// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.5.1
// source: calculator/calculatorpb/calcu.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Calcu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstNumber  int32 `protobuf:"varint,1,opt,name=firstNumber,proto3" json:"firstNumber,omitempty"`
	SecondNumber int32 `protobuf:"varint,2,opt,name=secondNumber,proto3" json:"secondNumber,omitempty"`
}

func (x *Calcu) Reset() {
	*x = Calcu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calcu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Calcu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calcu) ProtoMessage() {}

func (x *Calcu) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calcu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calcu.ProtoReflect.Descriptor instead.
func (*Calcu) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calcu_proto_rawDescGZIP(), []int{0}
}

func (x *Calcu) GetFirstNumber() int32 {
	if x != nil {
		return x.FirstNumber
	}
	return 0
}

func (x *Calcu) GetSecondNumber() int32 {
	if x != nil {
		return x.SecondNumber
	}
	return 0
}

type CalcuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calculation *Calcu `protobuf:"bytes,1,opt,name=calculation,proto3" json:"calculation,omitempty"`
}

func (x *CalcuRequest) Reset() {
	*x = CalcuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calcu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcuRequest) ProtoMessage() {}

func (x *CalcuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calcu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcuRequest.ProtoReflect.Descriptor instead.
func (*CalcuRequest) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calcu_proto_rawDescGZIP(), []int{1}
}

func (x *CalcuRequest) GetCalculation() *Calcu {
	if x != nil {
		return x.Calculation
	}
	return nil
}

type CalcuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalcuResponse) Reset() {
	*x = CalcuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calcu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcuResponse) ProtoMessage() {}

func (x *CalcuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calcu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcuResponse.ProtoReflect.Descriptor instead.
func (*CalcuResponse) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calcu_proto_rawDescGZIP(), []int{2}
}

func (x *CalcuResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculator_calculatorpb_calcu_proto protoreflect.FileDescriptor

var file_calculator_calculatorpb_calcu_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74, 0x22, 0x4d, 0x0a, 0x05,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x0c, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x52, 0x0b,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0d, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x44, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x12, 0x13, 0x2e,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_calculatorpb_calcu_proto_rawDescOnce sync.Once
	file_calculator_calculatorpb_calcu_proto_rawDescData = file_calculator_calculatorpb_calcu_proto_rawDesc
)

func file_calculator_calculatorpb_calcu_proto_rawDescGZIP() []byte {
	file_calculator_calculatorpb_calcu_proto_rawDescOnce.Do(func() {
		file_calculator_calculatorpb_calcu_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_calculatorpb_calcu_proto_rawDescData)
	})
	return file_calculator_calculatorpb_calcu_proto_rawDescData
}

var file_calculator_calculatorpb_calcu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_calculator_calculatorpb_calcu_proto_goTypes = []interface{}{
	(*Calcu)(nil),         // 0: greet.Calcu
	(*CalcuRequest)(nil),  // 1: greet.CalcuRequest
	(*CalcuResponse)(nil), // 2: greet.CalcuResponse
}
var file_calculator_calculatorpb_calcu_proto_depIdxs = []int32{
	0, // 0: greet.CalcuRequest.calculation:type_name -> greet.Calcu
	1, // 1: greet.CalcuService.Calcu:input_type -> greet.CalcuRequest
	2, // 2: greet.CalcuService.Calcu:output_type -> greet.CalcuResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_calculator_calculatorpb_calcu_proto_init() }
func file_calculator_calculatorpb_calcu_proto_init() {
	if File_calculator_calculatorpb_calcu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculator_calculatorpb_calcu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Calcu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calculatorpb_calcu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calculatorpb_calcu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_calculatorpb_calcu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_calculatorpb_calcu_proto_goTypes,
		DependencyIndexes: file_calculator_calculatorpb_calcu_proto_depIdxs,
		MessageInfos:      file_calculator_calculatorpb_calcu_proto_msgTypes,
	}.Build()
	File_calculator_calculatorpb_calcu_proto = out.File
	file_calculator_calculatorpb_calcu_proto_rawDesc = nil
	file_calculator_calculatorpb_calcu_proto_goTypes = nil
	file_calculator_calculatorpb_calcu_proto_depIdxs = nil
}
